@startuml

title YJU-capstone-team4
footer Page %page% of %lastpage%

actor 사용자 as User
actor 관리자 as Admin

collections App
collections Web
control 노드서버 as Node #99FF99
control 크롤링서버 as Lamda

== 지도 페이지 - 검색한 유튜버가 없을 때 ==
User -> App : 유튜버 검색 요청
activate User
' activate User #FFBBBB
activate App
App --> App : [ Youtube-API ]\n유튜버 채널 검색
App -> Node : [ Req ] 유튜버 channel id
deactivate App
alt 유튜버가 존재 할 경우
    Node --> Node : [ Query-Select ] 해당 유튜버가 다녀간\n가게 조회
else 유튜버가 존재하지 않을 경우
    Node -> App : [ Res ] statusCode :: 해당 유튜버의 데이터가 없습니다.
    App -> User : 해당 유튜버에 대한\n데이터 요청을 할 것인가?
    alt 유튜버 데이터 요청을 할 경우
        User -> App : 유튜버 데이터 요청
        App -> Node : [ Req ] 유튜버 Channel id, 이름, 구독자수, 전체 View
        Node --> Node : [ Query-Create ] 유튜버 신청건 저장
        Node -> App : [ Res ] statusCode :: 신청이 완료되었습니다.
        App -> User : 상태코드 모달창으로 화면 렌더링
    end
end
Node -> Web : [ Res ] 지역별 가게의\n총 개수 반환
Web -> User : 지역별 갯수를\n버블형태로 렌더링
deactivate User

@enduml
